export const users = [
  {
    displayName: "Test User 1",
    passwordProfile: { password: "TestPassword123-" },
    accountEnabled: true,
    mailNickname: "testuser1",
    userPrincipalName: "testuser15@sandboxfortest.onmicrosoft.com",
    city: "Redmond",
    // myCustomAttribute: "myCustomValue",
  },
  // {
  //   displayName: "Test User 2",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser2",
  //   userPrincipalName: "testuser2@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 3",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser3",
  //   userPrincipalName: "testuser3@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 4",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser4",
  //   userPrincipalName: "testuser4@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 5",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser5",
  //   userPrincipalName: "testuser5@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 6",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser6",
  //   userPrincipalName: "testuser6@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 7",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser7",
  //   userPrincipalName: "testuser7@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 8",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser8",
  //   userPrincipalName: "testuser8@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
  // {
  //   displayName: "Test User 9",
  //   passwordProfile: { password: "TestPassword123-" },
  //   accountEnabled: true,
  //   mailNickname: "testuser9",
  //   userPrincipalName: "testuser9@sandboxfortest.onmicrosoft.com",
  //   city: "Redmond",
  // },
];
